### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Esthyehenny**
According to the wireframe, users will initially see the welcome page before moving on to the categories page, therefore I changed home.html to index.html and vice versa. In accordance with the website Francesco forwarded to me, I also inserted async to the javascript tag. All javascript files will be able to synchronize with the page layout as a result.

To keep it current, all that is needed to do is merge the development branch with the main branch.

### CODE REVIEW

**Comment by FrnRmn** [comment]
Hi, thanks for the new updates. I have two points on that:

- **Working directly on the dev branch**: I thought we were going to adopt a 3 branch workflow. With every one of us that commits to their personal feature branch. -> Ask for a pull request to merge into dev. -> And only after, someone else reviews the changes and merges the feature branch into dev.
It seems you committed directly to Dev, skipping the feature branch and the PR review. Not a big deal this time, but just to be sure we understood each other, shouldn't we use feature branches to commit and wait for reviews for merges?

- **Merging to the main too soon** : in my opinion the main branch should be thought as "production". So it should contain a version of the product that is working (even if super minimal and bad looking). Isn't it too soon to merge to the main since the app is not a MVP?

Of course this is just my point of view, feel free to reply with your view on that @Esthyehenny @AaLin-Git !

**Comment by Esthyehenny** [comment]
Oh, I'm really sorry. I'll be careful next time.

**Comment by FrnRmn** [comment]
Don't worry :)
I fixed the style name, in the .html pages it was assigned to the wrong .css. Now it should look like Alona prepared it.
The rest is good for me!

**Comment by FrnRmn** [comment]
Should I merge it?

**Pull request merged**
